import AlertsPanel from "../components/AlertsPanel";

export default function Alerts() {
  return (
    <div className="content">
      <h2>⚠ Emergency Alerts Dashboard</h2>

      <div className="card" style={{ marginBottom: "20px" }}>
        <p style={{ opacity: 0.75, fontSize: "14px" }}>
          Real-time alerts generated by AI from the live CCTV feed.
        </p>
      </div>

      <AlertsPanel />
    </div>
  );
}
